batch_size: 128
clip_duration_ms: 1500
eval_step_interval: 500
features:
- features_dir: generated_features
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: true
  type: mmap
- features_dir: generated_features_negative
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
freq_mask_count:
- 2
freq_mask_max_size:
- 5
learning_rates:
- 0.001
maximization_metric: average_viable_recall
minimization_metric: null
negative_class_weight:
- 20
positive_class_weight:
- 1
target_minimization: 0.9
time_mask_count:
- 2
time_mask_max_size:
- 10
train_dir: trained_models/wakeword
training_steps:
- 10000
window_step_ms: 10