batch_size: 32
clip_duration_ms: 2000
eval_step_interval: 500
stride: 1
features:
- features_dir: /home/microWakeWord_data/generated_features_negatives_real
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_positives_final
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: true
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_ambient
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_negatives_tts
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_negatives_both
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_positives_both
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: true
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_positives_enhanced
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: true
  type: mmap
- features_dir: /home/microWakeWord_data/generated_features_hard_negatives
  penalty_weight: 1.0
  sampling_weight: 1.0
  truncation_strategy: random
  truth: false
  type: mmap
freq_mask_count:
- 2
freq_mask_max_size:
- 5
learning_rates:
- 0.001
maximization_metric: average_viable_recall
minimization_metric: null
negative_class_weight:
- 20
positive_class_weight:
- 1
target_minimization: 0.9
time_mask_count:
- 2
time_mask_max_size:
- 10
train_dir: trained_models/model_20250921_2043_neg_319k_bg_521k_pos_3k_total_843k_max_coverage_sampling_840k_samples_negatives_real_background_data
training_steps:
- 10000
window_step_ms: 10
